### ISSUE TITLE
Running on fastqs produces matrix full of "1"

### ISSUE THREAD

**Issue by EugeneBragin** [sanger-pathogens/saffrontree#13]
Running on bunch of fastq files, either .gz or ungzipped produces a matrix of identical distances full of 1s.
Running on fasta seems to work. Looks like it fails reading kmers from fastqs.

**Comment by andrewjpage** [comment]
Thanks for letting me know about the issue. I wrote the software a few years ago and it never really took off (and I havent used it myself).  I would probably use mashtree to solve this same problem now, so give it a shot: https://github.com/lskatz/mashtree
