### ISSUE TITLE
What is [&R] at start of .newick file?

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/saffrontree#5]
```
[&R] ('file1':888 ....
```

**Comment by andrewjpage** [comment]
It indicates the tree is rooted. The tree is generated by DendroPY:
http://dendropy.readthedocs.io/en/latest/tutorial/treemanips.html
I'm afraid I dont know what the history of this syntax update is.

**Comment by tseemann** [comment]
Figtree seemed to understand it, i've just never encountered it before!

I'm not sure if there is a true modern Newick specification.
